In [11]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

data = pd.read_csv("../data/titanic.csv")
data.head() ##check the first 5 lines

   sex   age  family_size     fare  1st_class  2nd_class  3rd_class  survived
0    1  22.0            1   7.2500          0          0          1         0
1    0  38.0            1  71.2833          1          0          0         1
2    0  26.0            0   7.9250          0          0          1         1
3    0  35.0            1  53.1000          1          0          0         1
4    1  35.0            0   8.0500          0          0          1         0

In [15]:
data.columns ##to get all features

Index(['sex', 'age', 'family_size', 'fare', '1st_class', '2nd_class',
       '3rd_class', 'survived'],
      dtype='str')

In [13]:
data.shape ##check the size of the data

(887, 8)

In [16]:
data.info() ##check missing values

<class 'pandas.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sex          887 non-null    int64
 1   age          887 non-null    float64
 2   family_size  887 non-null    int64
 3   fare         887 non-null    float64
 4   1st_class    887 non-null    int64
 5   2nd_class    887 non-null    int64
 6   3rd_class    887 non-null    int64
 7   survived     887 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 55.6 KB

In [17]:
data["survived"].value_counts()##show numbers

survived
0    545
1    342
Name: count, dtype: int64

In [18]:
data["survived"].value_counts(normalize=True) ##show percentages

survived
0    0.614431
1    0.385569
Name: proportion, dtype: float64

In [19]:
FEATURES = ["sex", "age", "family_size", "fare", "1st_class", "2nd_class", "3rd_class"]
TARGET = "survived"

features = data[FEATURES] ##take out the specific columns and make a new table
features.head()

   sex   age  family_size     fare  1st_class  2nd_class  3rd_class
0    1  22.0            1   7.2500          0          0          1
1    0  38.0            1  71.2833          1          0          0
2    0  26.0            0   7.9250          0          0          1
3    0  35.0            1  53.1000          1          0          0
4    1  35.0            0   8.0500          0          0          1

In [20]:
target = data[TARGET]
target.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

features: prepared input training data
target: training answers

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, random_state=42
) ## 20% as test set
print(f"Training set: {X_train.shape[0]} samples, Test set: {X_test.shape[0]} samples")

Training set: 709 samples, Test set: 178 samples